version: '3'
services:
  postgres:
    image: postgres:latest 
    environment:
      POSTGRES_DB: challenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"  # Map container port to host port
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data
  api:
    build: .
    ports:
      - "80:80"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/challenge
    env_file:
      - ./.env
volumes:
  postgres_data:
