version: '3'
services:
  postgres:
    image: postgres:latest 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: challenge
    ports:
      - "5432:5432"  # Map container port to host port
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data
  api:
    build: .
    command: bash -c "alembic upgrade head && uvicorn asgi:app --host 0.0.0.0 --port 80 --reload"
    ports:
      - "80:80"
    depends_on:
      - postgres
    env_file:
      - ./.env
volumes:
  postgres_data:
